### ISSUE TITLE
InvalidOperation Exception

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#61] opened 2015-05-04 19:22 UTC
Hi Tony,
I have yet another problem. I'll try to describe the problem to you.

Lets say I have a class Customer. I want to update one of its object. Lets say I want to update 100 fields. Instead of updating all fields, I have a xml version of that class, i just deserialize the xml to object, which gives me another Customer object. Then I update its primary key value. So newly created object has same primary as that of one which was fetched from database. Now when I am trying to ApplyChanges on the newly created object, I am getting following exception :

Attaching an entity of type 'X’ failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.

I have identiified the line :

https://github.com/tonysneed/trackable-entities/blob/release-2.5.1/Source/TrackableEntities.EF.5/DbContextExtensions.cs#L167

I think its because EF is thinking its a detached object, but somehow it is not able to merge new changes.

When I tried below code, it works :

var trackedEntity = context.Customers.Find(customer.Id);
context.Entry(trackedEntity).CurrentValues.SetValues(customer);
contex.ApplyChanges();

This issue is creating a major show stopped for smooth migration. Any thoughts ?

**Comment by harrisunderwork** [comment] 2015-05-05 09:13
Okay, when I detached old object and called ApplyChanges() on newly created object, it worked. I think the object fetched from database was being tracked and it was creating the problem. Strangely, this works in ef4.

**Comment by tonysneed** [comment] 2015-05-05 09:43
Great.  As you saw, this is an EF-specific exception, stating that the context already has an object attached with the same primary key.  I thought it was the same behavior in EF4, but maybe they changed that for EF 5 or 6.

**Comment by harrisunderwork** [comment] 2015-05-05 10:46
Tony,

Problem is we are migrating from ef4 to ef6 and that is creating lots of headaches :)

**Comment by harrisunderwork** [comment] 2015-05-05 10:52
Can we somehow integrate the code in TrackableEntities itself so nothing needs to be changed in business logic ?

I mean if exception is thrown while changing the state, we fetch the entity from database and apply currentvalues and retry setting the state ?

**Comment by tonysneed** [comment] 2015-05-05 10:57
Were you using DbContext in EF 4.x?  If so, that will help. There are a number of [breaking changes](https://msdn.microsoft.com/en-us/data/upgradeEF6).

**Comment by harrisunderwork** [comment] 2015-05-05 11:00
No Tony, I was using ObjectContext with EF4.

**Comment by tonysneed** [comment] 2015-05-05 11:27
ObjectContext is still there, as you know, but harder to get to.  Are you sticking with EDMX, or moving to code-based modeling?

PS, Here is a great intro video to using Git and GitHub with Visual Studio: http://channel9.msdn.com/Events/Build/2015/3-746

**Comment by tonysneed** [comment] 2015-05-05 11:50
I just saw your question above regarding exception handling.  I think I might need a bit more context to answer your question well.  Is the primary key a database-generated value?

**Comment by harrisunderwork** [comment] 2015-05-05 11:52
Thanks for the github video.

We are still using EDMX model as we have dedicated database custodian. He makes the changes and we generate edmx from it and then entities.

ObjectContext is useless now, we tried to use its methods but they make no sense now.

Yes we have database generated primary keys. I am still trying a sample to reload entities when exception occurs. Any thoughts are most welcomed.

**Comment by tonysneed** [comment] 2015-05-05 12:00
Not sure if I completely grasp the scenario, but I'll take a stab at being helpful.  When you retrieve a Customer from the database, you'll have the primary key which has been set by the database.  Then you deserialize the cached Customer, and, after starting change tracking, update all the fields on the retrieved Customer, except for the primary key.  The TrackingState will be Modified, and all the updated properties will be included in ModifiedProperties.  When you call ApplyChanges and SaveChanges, there shouldn't be any exception.

The key to the solution here is not calling ApplyChanges on the deserialized Customer, but copying the changed from the deserialized Customer over to the retrieved Customer and calling ApplyChanges on that, which will result in an update when SaveChanges is called.

If you want a simple way of determining which properties have changed, you can probably just write a bit of reflection code that iterates over the entity properties, sees which ones are different, and updates the retrieved Customer.

**Comment by harrisunderwork** [comment] 2015-05-05 12:04
**The key to the solution here is not calling ApplyChanges on the deserialized Customer, but copying the changed from the deserialized Customer over to the retrieved Customer and calling ApplyChanges on that, which will result in an update when SaveChanges is called.**

That's the thing I want to avoid, if I have the object that I want to update in database, why would I fetch it from database. I think your point is, it should be attach to context in order to be updated, right ?

**Comment by tonysneed** [comment] 2015-05-05 12:10
Hmmm ... Calling ApplyChanges is what attached an entity to the DbContext.  But the exception you're getting implies that you already attached an entity with the same primary key to the context.  So I guess I'm unclear about exactly why you're getting the exception ... Sorry if I'm being dense here. :confused:

**Comment by tonysneed** [comment] 2015-05-05 12:20
> Lets say I have a class Customer. I want to update one of its object. Lets say I want to update 100 fields. Instead of updating all fields, I have a xml version of that class, i just deserialize the xml to object, which gives me another Customer object. Then I update its primary key value. So newly created object has same primary as that of one which was fetched from database. Now when I am trying to ApplyChanges on the newly created object, I am getting following exception ...

From this I inferred that you have two Customer entities, both with the same primary key, which is the cause of the exception.  Where did you get the first one?

**Comment by tonysneed** [comment] 2015-05-05 12:23
PS. It might be easier if you were to create a small demo project in GitHub, which I could fork in order to see what you are trying to do. :grinning:

**Comment by harrisunderwork** [comment] 2015-05-05 12:29
Exactly, thats my point, but shouldn't that be handled by TE itself ?

**Comment by tonysneed** [comment] 2015-05-05 12:39
With TE, I'm trying to walk a very fine line.  I want to provide an easier way to apply change state in an object graph, but I don't want to handle exceptions which are thrown by EF because of a rule violation.

Can you explain to me more clearly how you end up with two entities?  Isn't one of them deserialized from XML and the other retrieved from the database?  Or am I missing something?

**Comment by harrisunderwork** [comment] 2015-05-05 12:59
Ahh, I guess your first comment explains a lot. Its an ef exception, I was just trying to figure out whether TE should handle EF exceptions or not. Actually we are migrating so I was thinking to do minimum changes at business level.

**Comment by tonysneed** [comment] 2015-05-05 17:23
Let me know if there are any lingering questions on this issue, and I'll re-open it.

Cheers,
Tony

**Closed by tonysneed** 2015-05-05 17:23 UTC

**Comment by harrisunderwork** [comment] 2015-05-06 09:00
Will handle EF related exceptions gracefully instead of TE catching them and solving by own.

Thanks.
